// export const GETTING_USER = 'GETTING_USER';// export const GOT_USER = 'GOT_USER';
// export const GOT_USER_ERROR = 'GOT_USER_ERROR';
export const UPDATE_SIZE = 'UPDATE_SIZE';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD_DIGEST = 'SET_PASSWORD_DIGEST';
export const SET_BIRTHDATE = 'SET_BIRTHDATE';
export const SHOW_SIGNUP_FORM = 'SHOW_SIGNUP_FORM';
export const CREATING_USER = 'CREATING_USER';
export const GET_AUTH_STATUS = 'GET_AUTH_STATUS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_LOGIN = 'SET_LOGIN';

export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';

export const GOT_USER_COORDS_ERROR = 'GOT_USER_COORDS_ERROR';
export const GOT_USER_COORDS = 'GOT_USER_COORDS';
export const GETTING_USER_COORDS = 'GETTING_USER_COORDS';

export const OPEN_BOTTOM_OVERLAY = 'OPEN_BOTTOM_OVERLAY';
export const CLOSE_BOTTOM_OVERLAY = 'CLOSE_BOTTOM_OVERLAY';

export const OPEN_TOP_OVERLAY = 'OPEN_TOP_OVERLAY';
export const CLOSE_TOP_OVERLAY = 'CLOSE_TOP_OVERLAY';

export const OPEN_PIN_MODAL = 'OPEN_PIN_MODAL';
export const CLOSE_PIN_MODAL = 'CLOSE_PIN_MODAL';

export const OPEN_STEPPER_MODAL = 'OPEN_STEPPER_MODAL';
export const CLOSE_STEPPER_MODAL = 'CLOSE_STEPPER_MODAL';

export const GOT_FAMILY_ERROR = 'GOT_FAMILY_ERROR';
export const GOT_FAMILY_PINS = 'GOT_FAMILY_PINS';
export const GETTING_FAMILY_PINS = 'GETTING_FAMILY_PINS';

export const GOT_PARTY_ERROR = 'GOT_PARTY_ERROR';
export const GOT_PARTY_PINS = 'GOT_PARTY_PINS';
export const GETTING_PARTY_PINS = 'GETTING_PARTY_PINS';

export const GOT_SPORTS_ERROR = 'GOT_SPORTS_ERROR';
export const GOT_SPORTS_PINS = 'GOT_SPORTS_PINS';
export const GETTING_SPORTS_PINS = 'GETTING_SPORTS_PINS';

export const CREATING_EVENT = 'CREATING_EVENT';
export const CREATED_EVENT = 'CREATED_EVENT';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_PRIVACY = 'SET_PRIVACY';
export const SET_EXPIRATION = 'SET_EXPIRATION';
