export const UPDATE_DIMENSIONS = 'UPDATE_DIMENSIONS';

export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';

export const GETTING_GEOLOCATION = 'GETTING_GEOLOCATION';
export const GOT_GEOLOCATION_SUCCESS = 'GOT_GEOLOCATION_SUCCESS';
export const GOT_GEOLOCATION_ERROR = 'GOT_GEOLOCATION_ERROR';
