export const UPDATE_SIZES = 'UPDATE_SIZES';

export const GETTING_USER_COORDS = 'GETTING_USER_COORDS';
export const GOT_USER_COORDS = 'GOT_USER_COORDS';
export const GOT_USER_COORDS_ERROR = 'GOT_USER_COORDS_ERROR';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD_DIGEST = 'SET_PASSWORD_DIGEST';
export const SET_BIRTHDATE = 'SET_BIRTHDATE';
export const SHOW_SIGNUP_FORM = 'SHOW_SIGNUP_FORM';
export const CREATING_USER = 'CREATING_USER';
export const GET_AUTH_STATUS = 'GET_AUTH_STATUS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_LOGIN = 'SET_LOGIN';
export const HIDE_SIGNIN = 'HIDE_SIGNIN';
export const HIDE_SIGNUP = 'HIDE_SIGNUP';
export const SHOW_SIGNIN = 'SHOW_SIGNIN';
export const SHOW_SIGNUP = 'SHOW_SIGNUP';
export const HIDE_MUST_BE_18 = 'HIDE_MUST_BE_18';

export const GET_CATEGORY_EVENTS = 'GET_CATEGORY_EVENTS';
export const GOT_EVENTS_ERROR = 'GOT_EVENTS_ERROR';
export const GOT_FAMILY_EVENTS = 'GOT_FAMILY_EVENTS';
export const GOT_PARTY_EVENTS = 'GOT_PARTY_EVENTS';
export const GOT_SPORTS_EVENTS = 'GOT_SPORTS_EVENTS';
export const SET_LOADED_TO_FALSE = 'SET_LOADED_TO_FALSE';

export const CREATING_EVENT = 'CREATING_EVENT';
export const CREATED_EVENT = 'CREATED_EVENT';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_PRIVACY = 'SET_PRIVACY';
export const SET_EXPIRATION = 'SET_EXPIRATION';

export const HIDE_BOTTOM_OVERLAY = 'HIDE_BOTTOM_OVERLAY';
export const HIDE_TOP_OVERLAY = 'HIDE_TOP_OVERLAY';
export const SHOW_BOTTOM_OVERLAY = 'SHOW_BOTTOM_OVERLAY';
export const SHOW_TOP_OVERLAY = 'SHOW_TOP_OVERLAY';
